FORMAT: 1A
HOST: http://emp.vts.it/vts-dpp-rest-api

# DPP

Service Oriented Architecture specified for the DPP project.

#######################
# Group Documents
#######################

## Documents Collection [/documents]

### Document types [GET /documents/types{?searchQuery}]
For details see documentation for [VMP Project/Documents/Documents Collection/Document types]

`searchQuery` parameter accepts following function values: `DPP_DPDOCS`, `DPP_SVCREC`, `DPP_VTSEMP`, `VMP_VEMP`.

This action is available only to `DPP_VENDOR_EMPLOYEE_READ`, `DPP_VENDOR_READ`, `DPP_CONTACT_READ`, `DPP_CONTRACT_READ`, `DPP_DOCUMENT_READ`, `DPP_SUBCONTRACTOR_READ`, `DPP_SERVICE_RECIPIENT_READ`, `DPP_DP_DOCUMENT_READ` roles.

+ Response 200

## Function `Entity Types` [/functions]

### Upload Document linking it to an entity [POST /functions/{functionId}/{entityId}/documents]

This action is available only to `DPP_VENDOR_EMPLOYEE_WRITE`, `DPP_VENDOR_WRITE`, `DPP_CONTACT_WRITE`, `DPP_CONTRACT_WRITE`, `DPP_DOCUMENT_WRITE`, `DPP_SUBCONTRACTOR_WRITE`, `DPP_SERVICE_RECIPIENT_WRITE`, `DPP_DP_DOCUMENT_WRITE` roles.

For details see documentation for [VMP Project/Documents/Documents Collection/Upload document linking it to an entity]

+ Response 201

### Download Document linked to an entity [GET /functions/{functionId}/{entityId}/documents/{id}]

This action is available only to `DPP_VENDOR_EMPLOYEE_READ`, `DPP_VENDOR_READ`, `DPP_CONTACT_READ`, `DPP_CONTRACT_READ`, `DPP_DOCUMENT_READ`, `DPP_SUBCONTRACTOR_READ`, `DPP_SERVICE_RECIPIENT_READ`, `DPP_DP_DOCUMENT_READ` roles.

For details see documentation for [VMP Project/Documents/Documents Collection/Download document linked to an entity]

+ Response 200

### Delete document linked to an entity [DELETE /functions/{functionId}/{entityId}/documents/{id}]

This action is available only to `DPP_VENDOR_EMPLOYEE_WRITE`, `DPP_VENDOR_WRITE`, `DPP_CONTACT_WRITE`, `DPP_CONTRACT_WRITE`, `DPP_DOCUMENT_WRITE`, `DPP_SUBCONTRACTOR_WRITE`, `DPP_SERVICE_RECIPIENT_WRITE`, `DPP_DP_DOCUMENT_WRITE` roles.

For details see documentation for [VMP Project/Documents/Documents Collection/Delete document linked to an entity]

+ Response 204

#######################
# Group DP Document
#######################

## DP Document Collection [/dpdocuments]

### List DP Document [GET /dpdocuments{?searchQuery,page,pageSize,sort,sortOrder}]
Search for links between a service request (vendor/subcontractor/vts) and a service recipient.

This action is available only to `DPP_DP_DOCUMENT_READ` role.

Takes a `searchQuery` parameter object defined as follows
* code (optional,number) - id of the link between a service request and a service recipient
* sreqid (optional,string) - internal id of the service request (vendor/subcontractor/vts) (syntax for not equal is allowed)
* srecid (optional,string) - internal id of the service recipient (syntax for not equal is allowed)
* sreqcode (optional,string) - master code of the service request (vendor/subcontractor/vts)
* sreccode (optional,string) - master code of the service recipient
* sreqname (optional,string) - name of the service request (vendor/subcontractor/vts)
* srecname (optional,string) - name of the service recipient
* sreqfunction (optional,string) - function id of the service request (VMP_VND or VMP_SUB or VMP_VTS)
* srecfunction (optional,string) - function id of the service recipient (DPP_SVCREC)


+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + pageSize: 25 (optional, number) - Amount of results to return
  + sort: default (enum[string], optional) - Sorting field
      + Members
          + default
          + sreqcode
          + sreqname
          + sreccode
          + srecname
  + sortOrder: asc (enum, optional) - Sorting order
      + Members
          + asc
          + desc

+ Response 200 (application/json)
  + Attributes (VendorLinkSearchResult)

### Create Temporary DP Document [POST /dpdocuments/temp]
Creates a new temporary and incomplete link between service request and service recipient.

This action is available only to `DPP_DP_DOCUMENT_WRITE` role.

+ Request (application/json)

+ Response 201 (application/json)

    + Headers

            Location: /dpdocuments/1

    + Attributes (VendorLinkTmp1)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



## DP Document [/dpdocuments/{id}]

+ Parameters
  + id: 1 (required) - id of the requested link between vendors

+ Attributes (VendorLink)

### Read DP Document [GET]
Used to retrieve link between service request and service recipient detail.

This action is available only to `DPP_DP_DOCUMENT_READ` role.

+ Response 200 (application/json)

    + Attributes (VendorLink1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update DP Document [PUT]
Used to update link between service request and service recipient details.

This action is available only to `DPP_DP_DOCUMENT_WRITE` role.

+ Parameters
    + id: 1 (required, number) - id of the link between vendors

+ Request (application/json)
  + Attributes (VendorLink1)

+ Response 200
  + Attributes (VendorLink1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete DP Document [DELETE]
Used to delete a link between service request and service recipient.
the link is permanently deleted with all associated documents

This action is available only to `DPP_DP_DOCUMENT_WRITE` role.

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

## DP Document Inquiry [/dpdocuments/inquiry]

### List DP Document Inquiry [GET /dpdocuments/inquiry{?searchQuery,page,pageSize,sort,sortOrder}]
Search for documents associated to DP document

This action is available only to `DPP_DP_DOCUMENT_READ` role.

Takes a `searchQuery` parameter object defined as follows
* code (optional,number) - id of the link between a service request and a service recipient
* sreqid (optional,string) - internal id of the service request (vendor/subcontractor/vts) (syntax for not equal is allowed)
* srecid (optional,string) - internal id of the service recipient (syntax for not equal is allowed)
* sreqcode (optional,string) - master code of the service request (vendor/subcontractor/vts)
* sreccode (optional,string) - master code of the service recipient
* sreqname (optional,string) - name of the service request (vendor/subcontractor/vts)
* srecname (optional,string) - name of the service recipient
* sreqfunction (optional,string) - function id of the service request (VMP_VND or VMP_SUB or VMP_VTS)
* srecfunction (optional,string) - function id of the service recipient (DPP_SVCREC)


+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + pageSize: 25 (optional, number) - Amount of results to return
  + sort: default (enum[string], optional) - Sorting field
      + Members
          + default
          + sreqcode
          + sreqname
          + sreccode
          + srecname
  + sortOrder: asc (enum, optional) - Sorting order
      + Members
          + asc
          + desc

+ Response 200 (application/json)
  + Attributes (VendorLinkInquirySearchResult)


#######################
# Group Service Recipient
#######################

## Service Recipient Collection [/servicerecipients]

### List Service Recipients [GET /servicerecipients{?searchQuery,page,pageSize,sort,sortorder,report}]
Search for service recipients.

This action works exactly as [VMP Project/Vendor/Vendor collection/Vendor list], with the only difference that only
Vendors classified as DPP_SVCREC will be returned.

This action is available only to `DPP_SERVICE_RECIPIENT_READ`, `DPP_DP_DOCUMENT_READ` roles.

### Create Service Recipient [POST]
Creates a service recipient. This action works exactly as [VMP Project/Vendor/Vendor collection/Create vendor],
with the only difference that it will fail if one tries to create a Vendor which is not classified as DPP_SVCREC.

This action is available only to `DPP_SERVICE_RECIPIENT_WRITE` role.

## Service Recipient [/servicerecipients/{id}]

### Read Service Recipient [GET]
Reads a service recipient. This action works exactly as [VMP Project/Vendor/Vendor/Read vendor],
with the only difference that only Vendors classified as DPP_SVCREC will be returned.

This action is available only to `DPP_SERVICE_RECIPIENT_READ` role.

### Update Service Recipient [PUT]
Updates a service recipient. This action works exactly as [VMP Project/Vendor/Vendor/Update vendor],
with the only difference that it will fail if one tries to update a Vendor which is not classified as DPP_SVCREC.

This action is available only to `DPP_SERVICE_RECIPIENT_WRITE` role.

### Delete Service Recipient [DELETE]
Deletes a service recipient. This action works exactly as [VMP Project/Vendor/Vendor/Delete vendor],
with the only difference that it will fail if one tries to delete a Vendor which is not classified as DPP_SVCREC.

This action is available only to `DPP_SERVICE_RECIPIENT_WRITE` role.

#######################
# Group Lookup Lists
#######################

## DP Document status collection [/lookup/dpdocumentstatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: A
          + description: Active
  + paginationData (object, required) - Informations required for pagination
        + count: 1 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List DP Document status [GET]

The list of DP Document status.

This action does not require authentication.

+ Response 200 (application/json)
  + Attributes (DP Document status collection)

## Service Recipient status collection [/lookup/servicerecipientstatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: A
          + description: Active
      + (object)
          + id: B
          + description: Blocked
      + (object)
          + id: M
          + description: Marked for deletion
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List service recipient status [GET]

The list of service recipient status.

This action does not require authentication.

+ Response 200 (application/json)
  + Attributes (Service Recipient status collection)


#######################
# Data Structures
#######################

## PaginationData1
+ paginationData (object, required) - Informations required for pagination
    + count: 3 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 25 (number, required) - size of the slice

## VendorLinkSearchResult
+ results (array[VendorLink1, VendorLink2, VendorLink3], required) - array of links between vendors
+ Include PaginationData1

## VendorLink1 (VendorLink)
+ id: 1 (number)
+ vendor1 (ServiceRequest1)
+ vendor2 (ServiceRecipient1)

## VendorLink2 (VendorLink)
+ id: 2 (number)
+ vendor1 (ServiceRequest2)
+ vendor2 (ServiceRecipient2)

## VendorLink3 (VendorLink)
+ id: 3 (number)
+ vendor1 (ServiceRequest3)
+ vendor2 (ServiceRecipient3)

## VendorLink (VendorLinkInsert)
+ id (number)- id of dp document aka link

## VendorLinkInsert
+ vendor1 (ServiceRequest) - see [Vendor documentation](http://docs.vmp2016.apiary.io/#reference/vendor/vendor) for single fields. Notice that the Vendor returned here doesn't have all fields populated. When creating a new link, only the id is considered, but it must belong to an active vendor.
+ vendor2 (ServiceRecipient) - see [Vendor documentation](http://docs.vmp2016.apiary.io/#reference/vendor/vendor) for single fields. Notice that the Vendor returned here doesn't have all fields populated. When creating a new link, only the id is considered, but it must belong to an active vendor.
+ status (StatusActive) - When inserting, only the id is considered.
+ notes - text up to 2000 characters long

## ServiceRecipient1 (ServiceRecipient)
+ id: 144 (number)
+ name: CONSORZIO QUENIT
+ masterCode: SR000144

## ServiceRecipient2 (ServiceRecipient)
+ id: 188 (number)
+ name: UNICREDIT FACTORING SPA / MILANO / IT
+ masterCode: SR000188

## ServiceRecipient3 (ServiceRecipient)
+ id: 985 (number)
+ name: CASSA DI RISPARMIO DI CESENA
+ masterCode: SR000985

## ServiceRequest1 (ServiceRequest)
+ id: 150
+ name: Matrix tecnology
+ masterCode: 4000047

## ServiceRequest2 (ServiceRequest)
+ id: 130
+ name: COMAPP S.r.l.
+ masterCode: 4000500

## ServiceRequest3 (ServiceRequest)
+ id: 355
+ name: NETEXPRESS GMBH
+ masterCode: 4000355

## ServiceRequest
+ id: 150 (number) - Service request internal code
+ name: Matrix tecnology  (string) - Service request description
+ masterCode: 4000047 (string) - Service request master code
+ functionId: VMP_VND (enum)
    + VMP_VND - Vendors
    + VMP_SUB - Subcontractors
    + VMP_VTS - VTS

## ServiceRecipient
+ id: 144 (number) - Service recipient internal code
+ name: CONSORZIO QUENIT (string) - Service recipient description
+ masterCode: SR000144 (string) - Service recipient master code
+ functionId: DPP_SVCREC (enum)
    + DPP_SVCREC - Service recipients

## LookupData
+ id
+ description

## StatusTmp
+ id: TMP (string)
+ description : Temporary (string)

## StatusActive
+ id: A (string)
+ description : Active (string)

## VendorLinkTmp1 (VendorLinkTmp)
+ id: 1 (number)

## VendorLinkTmp
+ status (StatusTmp) - temporary status

##DocumentType1 (object)
+ id: 132
+ description: `DPL`

##DocumentType2 (object)
+ id: 133
+ description: `IBM Checklist`

##DocumentType3 (object)
+ id: 161
+ description: `Supplier questioinnaire`

##FunctionDPD
+ id: `DPP_DPDOCS` (string, required) - function id

## FileInfo1 (object)
+ id: 3220 (number) - file id
+ fileName: `New_sup_R&D_L.pdf` (string) - file name
+ description: `file desciption` (string) - file description

## FileInfo2 (object)
+ id: 3221 (number) - file id
+ fileName: `report3.doc` (string) - file name
+ description: `file desciption` (string) - file description

## FileInfo3 (object)
+ id: 3222 (number) - file id
+ fileName: `report.doc` (string) - file name
+ description: `file desciption` (string) - file description

## DocumentInfo1 (object)
+ entityId: 1 (number, optional)
+ documentFile (FileInfo1)
+ description: `New supplier R&D legal`
+ insertDate: `2016-02-06 10.50.30`
+ signingDate: `2016-02-06`
+ validityDate: `2016-02-06`
+ function (FunctionDPD)
+ docType (DocumentType1, required)

## DocumentInfo2 (object)
+ entityId: 2 (number, optional)
+ documentFile (FileInfo2)
+ description: `performance NTT Data Austria`
+ insertDate: `2016-02-08 10.50.30`
+ function (FunctionDPD)
+ docType (DocumentType2, required)

## DocumentInfo3 (object)
+ entityId: 3 (number, optional)
+ documentFile (FileInfo3)
+ description: `Supplier questioinnaire BRUTTI L`
+ insertDate: `2016-02-10 10.50.30`
+ signingDate: `2016-02-10`
+ function (FunctionDPD)
+ docType (DocumentType3, required)

## VendorLinkInquiry1
+ vendorLink (VendorLink1) - DP document link information
+ document (DocumentInfo1) - document information

## VendorLinkInquiry2
+ vendorLink (VendorLink2) - DP document information
+ document (DocumentInfo2) - document information

## VendorLinkInquiry3
+ vendorLink (VendorLink3) - DP document information
+ document (DocumentInfo3) - document information

## VendorLinkInquirySearchResult
+ results (array[VendorLinkInquiry1, VendorLinkInquiry2, VendorLinkInquiry3], required) - array of documents associated to dp document
+ Include PaginationData1
