FORMAT: 1A
HOST: http://emp.vts.it/vts-dpp-rest-api

# DPP

Service Oriented Architecture specified for the DPP project.

#######################
# Group Documents
#######################

## Documents Collection [/documents]

### Document types [GET /documents/types{?searchQuery}]
For details see [VMP Project](http://docs.vmp2016.apiary.io/#reference/documents/documents-collection/document-types) documentation.

`searchQuery` parameter accepts following function values: `DPP_DPDOCS`, `DPP_SVCREC`, `DPP_VTSEMP`, `VMP_VEMP`.

+ Response 200

## Function `Entity Types` [/functions]

### Upload Document linking it to an entity [POST /functions/{functionId}/{entityId}/documents]
For details see [VMP Project](http://docs.vmp2016.apiary.io/#reference/documents/function-entity-types/upload-document-linking-it-to-an-entity) documentation.

+ Response 201

### Download Document linked to an entity [GET /functions/{functionId}/{entityId}/documents/{id}]
For details see [VMP Project](http://docs.vmp2016.apiary.io/#reference/documents/function-entity-types/download-document-linked-to-an-entity) documentation.

+ Response 200

### Delete document linked to an entity [DELETE /functions/{functionId}/{entityId}/documents/{id}]
For details see [VMP Project](http://docs.vmp2016.apiary.io/#reference/documents/function-entity-types/delete-document-linked-to-an-entity) documentation.

+ Response 204

#######################
# Group DP Document 
#######################

## DP Document Collection [/dpdocuments]

### List DP Document [GET /dpdocuments{?searchQuery,page,pageSize,sort,sortorder,report}]
Search for links between a service request (vendor/subcontractor/vts) and a service recipient.

This action is available only to **TODO** roles.

Takes a `searchQuery` parameter object defined as follows
* code (optional,number) - id of the link between a service request and a service recipient 
* sreqid (optional,number) - internal id of the service request (vendor/subcontractor/vts)
* srecid (optional,number) - internal id of the service recipient 
* sreqcode (optional,string) - master code of the service request (vendor/subcontractor/vts)
* sreccode (optional,string) - master code of the service recipient
* sreqname (optional,string) - name of the service request (vendor/subcontractor/vts)
* srecname (optional,string) - name of the service recipient
* sreqfunction (optional,string) - function id of the service request (VMP_VND or VMP_SUB or VMP_VTS) 
* srecfunction (optional,string) - function id of the service recipient (DPP_SVCREC)


+ Parameters
  + searchQuery: {} (object, required) - json filter
  + page: 1 (optional, number) - The page of results to return
  + pageSize: 25 (optional, number) - Amount of results to return
  + sort: default (enum[string], optional) - Sorting field
      + Members
          + default
          + svcreqcode
          + svcreqname
          + svcreccode
          + svcrecname
  + sortOrder: asc (enum, optional) - Sorting order
      + Members
          + asc
          + desc
  + report: SVCRCP (enum[string], optional) - Type of report (**throws error when invalid value**)
      + Members
          + SVCRCP
          + PREVIEW

+ Response 200 (application/json)
  + Attributes (VendorLinkSearchResult)

### Create DP Document [POST]
Creates a new link between vendors.

This action is available only to **TODO** role.

+ Request (application/json)

    + Attributes (VendorLinkInsert)

+ Response 201 (application/json)

    + Headers

            Location: /dpdocuments/123

    + Attributes (VendorLink)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body


### Create Temporary DP Document [POST /dpdocuments/temp]
Creates a new temporary dp document.

This action is available only to **TODO** role.

+ Request (application/json)

+ Response 201 (application/json)

    + Headers

            Location: /dpdocuments/1

    + Attributes (VendorLinkTmp1)

+ Response 400
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



## DP Document [/dpdocuments/{id}]

+ Parameters
  + id: 1 (required) - id of the requested link between vendors

+ Attributes (VendorLink)

### Read DP Document [GET]
Used to retrieve link between service request and service recipient detail.

This action is available only to **TODO** role.

+ Response 200 (application/json)

    + Attributes (VendorLink)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Update DP Document [PUT]
Used to update link between service request and service recipient details.

This action is available only to **TODO** role.

+ Parameters
    + id: 1 (required, number) - id of the link between vendors

+ Request (application/json)
  + Attributes (VendorLink1)

+ Response 200
  + Attributes (VendorLink1)

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body

### Delete DP Document [DELETE]
Used to delete a link between service request and service recipient.

This action is available only to  **TODO** role.

+ Response 204

+ Response 404
    Returned when the required resource cannot be found.

    + Body

+ Response 500
    Returned when a generic error occours.

    + Body



#######################
# Group Service Recipient
#######################

## Service Recipient Collection [/servicerecipients]

### List Service Recipients [GET /servicerecipients{?searchQuery,page,pageSize,sort,sortorder,report}]
Search for service recipients.

This action works exactly as [VMP List Vendor](http://docs.vmp2016.apiary.io/#reference/vendor/vendor-collection/list-vendor), with the only difference that only
Vendors classified as DPP_SVCREC will be returned.

**TODO: double-check, why this exists then?**

This action is available only to **TODO** role.

### Create Service Recipient [POST]
Creates a service recipient. This action works exactly as [VMP Create Vendor](http://docs.vmp2016.apiary.io/#reference/vendor/vendor-collection/create-vendor),
with the only difference that it will fail if one tries to create a Vendor which is not classified as DPP_SVCREC.

**TODO: double-check, why this exists then?**

This action is available only to **TODO** role.

## Service Recipient [/servicerecipients/{id}]

### Read Service Recipient [GET]
Reads a service recipient. This action works exactly as [VMP Read Vendor](http://docs.vmp2016.apiary.io/#reference/vendor/vendor/read-vendor),
with the only difference that only Vendors classified as DPP_SVCREC will be returned.

**TODO: double-check, why this exists then?**

This action is available only to **TODO** role.

### Update Service Recipient [PUT]
Updates a service recipient. This action works exactly as [VMP Update Vendor](http://docs.vmp2016.apiary.io/#reference/vendor/vendor/update-vendor),
with the only difference that it will fail if one tries to update a Vendor which is not classified as DPP_SVCREC.

**TODO: double-check, why this exists then?**

This action is available only to **TODO** role.

### Delete Service Recipient [DELETE]
Deletes a service recipient. This action works exactly as [VMP Delete Vendor](http://docs.vmp2016.apiary.io/#reference/vendor/vendor/delete-vendor),
with the only difference that it will fail if one tries to delete a Vendor which is not classified as DPP_SVCREC.

**TODO: double-check, why this exists then?**

This action is available only to **TODO** role.

#######################
# Group Lookup Lists
#######################

## DP Document status collection [/lookup/dpdocumentstatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: A
          + description: Active
  + paginationData (object, required) - Informations required for pagination
        + count: 1 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List DP Document status [GET]

The list of DpDocument status.

This action does not require authentication.

+ Response 200 (application/json)
  + Attributes (DP Document status collection)

## Service Recipient status collection [/lookup/servicerecipientstatus]

+ Attributes (object)
  + results (array, required) - array of resources
      + (object)
          + id: A
          + description: Active
      + (object)
          + id: B
          + description: Blocked
      + (object)
          + id: M
          + description: Marked for deletion
  + paginationData (object, required) - Informations required for pagination
        + count: 3 (number,required) - total number of resources
        + pageNum: 1 (number, required) - slice of resources returned
        + pageSize: 25 (number, required) - size of the slice


### List service recipient status [GET]

The list of service recipient status.

This action does not require authentication.

+ Response 200 (application/json)
  + Attributes (Service Recipient status collection)


#######################
# Data Structures
#######################

## PaginationData1
+ paginationData (object, required) - Informations required for pagination
    + count: 3 (number,required) - total number of resources
    + pageNum: 1 (number, required) - slice of resources returned
    + pageSize: 25 (number, required) - size of the slice

## VendorLinkSearchResult
+ results (array[VendorLink1, VendorLink2, VendorLink3], required) - array of links between vendors
+ Include PaginationData1

## VendorLink1 (VendorLink)
+ id: 1 (number)
+ vendor1 (ServiceRequest1) 
+ vendor2 (ServiceRecipient1) 

## VendorLink2 (VendorLink)
+ id: 2 (number)
+ vendor1 (ServiceRequest2) 
+ vendor2 (ServiceRecipient2) 

## VendorLink3 (VendorLink)
+ id: 3 (number)

## VendorLink (VendorLinkInsert)
+ id (number)- id of the link

## VendorLinkInsert
+ vendor1 (ServiceRequest) - see [Vendor documentation](http://docs.vmp2016.apiary.io/#reference/vendor/vendor) for single fields. Notice that the Vendor returned here doesn't have all fields populated. When creating a new link, only the id is considered, but it must belong to an active vendor.
+ vendor2 (ServiceRecipient) - see [Vendor documentation](http://docs.vmp2016.apiary.io/#reference/vendor/vendor) for single fields. Notice that the Vendor returned here doesn't have all fields populated. When creating a new link, only the id is considered, but it must belong to an active vendor.
+ status (StatusActive) - When inserting, only the id is considered.
+ notes - text up to 2000 characters long

## ServiceRecipient1 (ServiceRecipient)
+ id: 144 (number)
+ name: CONSORZIO QUENIT
+ masterCode: SR000144

## ServiceRecipient2 (ServiceRecipient)
+ id: 188 (number)
+ name: UNICREDIT FACTORING SPA / MILANO / IT
+ masterCode: SR000188

## ServiceRequest1 (ServiceRequest)
+ id: 150 
+ name: Matrix tecnology 
+ masterCode: 4000047

## ServiceRequest2 (ServiceRequest)
+ id: 130 
+ name: COMAPP S.r.l. 
+ masterCode: 4000500

## ServiceRequest
+ id (number) - Service request internal code
+ name (string) - Service request description 
+ masterCode (string) - Service request master code
+ functionId: VMP_VND (enum)
    + VMP_VND - Vendors
    + VMP_SUB - Subcontractors
    + VMP_VTS - VTS

## ServiceRecipient
+ id (number) - Service recipient internal code
+ name (string) - Service recipient description 
+ masterCode (string) - Service recipient master code
+ functionId: DPP_SVCREC (enum)
    + DPP_SVCREC - Service recipients

## LookupData
+ id
+ description

## StatusTmp
+ id: TMP (string)
+ description : Temporary (string)

## StatusActive
+ id: A (string)
+ description : Active (string)

## VendorLinkTmp1 (VendorLinkTmp)
+ id: 1 (number)

## VendorLinkTmp
+ status (StatusTmp) - temporary status